// This work is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
// https://creativecommons.org/licenses/by-nc-sa/4.0/

// © Zeiierman {
//@version=6
indicator('Dynamic Swing Anchored VWAP (Zeiierman)', overlay = true, max_bars_back = 5000, max_labels_count = 500, max_polylines_count = 100)

prd     = input.int(50, title='Swing Period', minval=2, group='Swing Points')
baseAPT = input.float(20, 'Adaptive Price Tracking', minval=1, step=1, group='Swing Points')
useAdapt = input.bool(false, 'Adapt APT by ATR ratio', group='Swing Points')
volBias = input.float(10.0, 'Volatility Bias', minval=0.1, step=0.1, group='Swing Points')

ph  := ta.highestbars(high, prd) == 0 ? high : ph
pl  := ta.lowestbars(low,  prd) == 0 ? low  : pl
phL := ta.highestbars(high, prd) == 0 ? b   : phL
plL := ta.lowestbars(low,  prd) == 0 ? b    : plL
dir = phL > plL ? 1 : -1

// Direction change = swing confirmed
// dir -1 -> 1 = swing low confirmed (BUY)
// dir 1 -> -1 = swing high confirmed (SELL)
